<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CsvHelper" Version="33.1.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.8" />
	</ItemGroup>


	<ItemGroup>
		<None Update="Application\appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>


	<ItemGroup>
	  <Folder Include="Application\Models\" />
	  <Folder Include="Domain\Contracts\Services\" />
	</ItemGroup>


</Project>
